### ISSUE TITLE
'make test' is panic-ing

### ISSUE THREAD

**Issue by vimalk78** [ViaQ/logerr#12]
```vimalkum (master) logerr $ make test
go test -race ./...
?   	github.com/ViaQ/logerr/internal/kv	[no test files]
ok  	github.com/ViaQ/logerr/kverrors	(cached)
--- FAIL: TestError (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x86c143]

goroutine 43 [running]:
testing.tRunner.func1.1(0x8b7860, 0xc28880)
	/usr/local/go/src/testing/testing.go:988 +0x452
testing.tRunner.func1(0xc000145c20)
	/usr/local/go/src/testing/testing.go:991 +0x600
panic(0x8b7860, 0xc28880)
	/usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/ViaQ/logerr/log_test.TestError(0xc000145c20)
	/home/vimalkum/go/src/github.com/ViaQ/logerr/log/log_test.go:85 +0x2e3
testing.tRunner(0xc000145c20, 0x931000)
	/usr/local/go/src/testing/testing.go:1039 +0x1ec
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1090 +0x701
FAIL	github.com/ViaQ/logerr/log	0.013s
FAIL
make: *** [Makefile:13: test] Error 1
```

**Comment by blockloop** [comment]
This was fixed in #13 I believe
