### ISSUE TITLE
Panic with encoding

### ISSUE THREAD

**Issue by jcantrill** [ViaQ/logerr#8]
```
$ go version
go version go1.14.7 linux/amd64

$ cat go.sum | grep logerr
github.com/ViaQ/logerr v1.0.5 h1:4XvfyJv+qZjDESI6myrnaJcPov7oKVKd53obLaZOEhI=
github.com/ViaQ/logerr v1.0.5/go.mod h1:YqNHnxR3/VF46GXbGvi+hYz1BWI+yUwr+3CZg1933Hw=


goroutine 1309 [running]:
runtime.throw(0x170950f, 0x21)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00074d2e8 sp=0xc00074d2b8 pc=0x435482
runtime.mapaccess2(0x150c9c0, 0xc0003a03c0, 0xc00062a700, 0xc00062a700, 0xc0007e2a7b)
	/usr/local/go/src/runtime/map.go:469 +0x258 fp=0xc00074d328 sp=0xc00074d2e8 pc=0x40fc28
reflect.mapaccess(0x150c9c0, 0xc0003a03c0, 0xc00062a700, 0x16fb3f7)
	/usr/local/go/src/runtime/map.go:1309 +0x3f fp=0xc00074d360 sp=0xc00074d328 pc=0x411e3f
reflect.Value.MapIndex(0x150c9c0, 0xc0003a03c0, 0x15, 0x14b19c0, 0xc00062a700, 0x98, 0x14ee800, 0xc00062a780, 0x94)
	/usr/local/go/src/reflect/value.go:1173 +0x16d fp=0xc00074d3d8 sp=0xc00074d360 pc=0x4b6bbd
encoding/json.mapEncoder.encode(0x17afd50, 0xc0003ab500, 0x150c9c0, 0xc0003a03c0, 0x15, 0x1500100)
	/usr/local/go/src/encoding/json/encode.go:801 +0x305 fp=0xc00074d550 sp=0xc00074d3d8 pc=0x50be25
encoding/json.mapEncoder.encode-fm(0xc0003ab500, 0x150c9c0, 0xc0003a03c0, 0x15, 0x2480100)
	/usr/local/go/src/encoding/json/encode.go:777 +0x64 fp=0xc00074d590 sp=0xc00074d550 pc=0x517e34
encoding/json.(*encodeState).reflectValue(0xc0003ab500, 0x150c9c0, 0xc0003a03c0, 0x15, 0xc000740100)
	/usr/local/go/src/encoding/json/encode.go:358 +0x82 fp=0xc00074d5c8 sp=0xc00074d590 pc=0x508fa2
encoding/json.(*encodeState).marshal(0xc0003ab500, 0x150c9c0, 0xc0003a03c0, 0xd21c829bc030100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:330 +0xf0 fp=0xc00074d628 sp=0xc00074d5c8 pc=0x508ac0
encoding/json.(*Encoder).Encode(0xc00074d6e0, 0x150c9c0, 0xc0003a03c0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:206 +0x8a fp=0xc00074d6b8 sp=0xc00074d628 pc=0x515a3a
github.com/ViaQ/logerr/log.JSONEncoder.Encode(...)
	/home/jeff.cantrill/git/cluster-logging-operator/vendor/github.com/ViaQ/logerr/log/encoding.go:13
github.com/ViaQ/logerr/log.(*JSONEncoder).Encode(0x24bb440, 0x1904d80, 0xc000010018, 0xc0003a03c0, 0xc00074d8d0, 0x203000)
	<autogenerated>:1 +0xbe fp=0xc00074d740 sp=0xc00074d6b8 pc=0xc441de
github.com/ViaQ/logerr/log.(*Logger).log(0xc000550900, 0x170d5ae, 0x24, 0xc0003a03c0)
	/home/jeff.cantrill/git/cluster-logging-operator/vendor/github.com/ViaQ/logerr/log/logger.go:91 +0x24f fp=0xc00074d948 sp=0xc00074d740 pc=0xc4353f
github.com/ViaQ/logerr/log.(*Logger).Info(0xc000550900, 0x170d5ae, 0x24, 0xc000a11600, 0x2, 0x2)
	/home/jeff.cantrill/git/cluster-logging-operator/vendor/github.com/ViaQ/logerr/log/logger.go:109 +0xa0 fp=0xc00074d978 sp=0xc00074d948 pc=0xc437b0
github.com/ViaQ/logerr/log.(*Logger).Error(0xc000550900, 0x19031c0, 0xc0005a98d0, 0x170d5ae, 0x24, 0x0, 0x0, 0x0)
	/home/jeff.cantrill/git/cluster-logging-operator/vendor/github.com/ViaQ/logerr/log/logger.go:137 +0x11c fp=0xc00074d9e0 sp=0xc00074d978 pc=0xc438ec
github.com/ViaQ/logerr/log.Error(0x19031c0, 0xc00062a5f0, 0x170d5ae, 0x24, 0x0, 0x0, 0x0)
	/home/jeff.cantrill/git/cluster-logging-operator/vendor/github.com/ViaQ/logerr/log/log.go:111 +0xd0 fp=0xc00074da48 sp=0xc00074d9e0 pc=0xc42bb0
github.com/openshift/cluster-logging-operator/pkg/k8shandler.(*ClusterLoggingRequest).generateCollectorConfig(0xc00020c620, 0x16fd01f, 0x18, 0x0, 0x0)
	/home/jeff.cantrill/git/cluster-logging-operator/pkg/k8shandler/forwarding.go:62 +0x3ca fp=0xc00074db10 sp=0xc00074da48 pc=0x120e5ba
github.com/openshift/cluster-logging-operator/pkg/k8shandler.(*ClusterLoggingRequest).CreateOrUpdateCollection(0xc00020c620, 0xc00054c680, 0x11c4356, 0xc0008eabe0)
	/home/jeff.cantrill/git/cluster-logging-operator/pkg/k8shandler/collection.go:72 +0x257 fp=0xc00074dbb8 sp=0xc00074db10 pc=0x11fe5c7
github.com/openshift/cluster-logging-operator/pkg/k8shandler.ReconcileForGlobalProxy(0xc00054c680, 0x194e320, 0xc0006970e0, 0x0, 0x0)
	/home/jeff.cantrill/git/cluster-logging-operator/pkg/k8shandler/reconciler.go:122 +0x162 fp=0xc00074dc38 sp=0xc00074dbb8 pc=0x1218c42
github.com/openshift/cluster-logging-operator/pkg/controller/proxyconfig.(*ReconcileProxyConfig).Reconcile(0xc000320a60, 0x0, 0x0, 0xc0007e7760, 0x7, 0x0, 0xbfe62bdb92bcad4f, 0xc000110510, 0xc000110488)
	/home/jeff.cantrill/git/cluster-logging-operator/pkg/controller/proxyconfig/proxyconfig_controller.go:95 +0x1a0 fp=0xc00074dcb8 sp=0xc00074dc38 pc=0x135e0c0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001ecb40, 0x157d820, 0xc0008a1d40, 0x0)
	/home/jeff.cantrill/git/cluster-logging-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x161 fp=0xc00074ddd8 sp=0xc00074dcb8 pc=0x129b691
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001ecb40, 0x203000)
	/home/jeff.cantrill/git/cluster-logging-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xae fp=0xc00074de30 sp=0xc00074ddd8 pc=0x129b4ce
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001ecb40)
	/home/jeff.cantrill/git/cluster-logging-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b fp=0xc00074de50 sp=0xc00074de30 pc=0x129b3fb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker-fm()
	/home/jeff.cantrill/git/cluster-logging-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:210 +0x2a fp=0xc00074de68 sp=0xc00074de50 pc=0x129d00a
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0007741b0)
	/home/jeff.cantrill/git/cluster-logging-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f fp=0xc00074deb8 sp=0xc00074de68 pc=0xba426f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0007741b0, 0x1904360, 0xc000810510, 0x1, 0xc00055e1e0)
	/home/jeff.cantrill/git/cluster-logging-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3 fp=0xc00074df58 sp=0xc00074deb8 pc=0xba30a3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007741b0, 0x3b9aca00, 0x0, 0x1, 0xc00055e1e0)
	/home/jeff.cantrill/git/cluster-logging-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98 fp=0xc00074df90 sp=0xc00074df58 pc=0xba2fe8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0007741b0, 0x3b9aca00, 0xc00055e1e0)
	/home/jeff.cantrill/git/cluster-logging-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d fp=0xc00074dfc8 sp=0xc00074df90 pc=0xba2f3d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00074dfd0 sp=0xc00074dfc8 pc=0x465341
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/jeff.cantrill/git/cluster-logging-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x305
```

**Comment by jcantrill** [comment]
did a 'make clean' and reran... maybe its just bad env

**Comment by jcantrill** [comment]
Still here.. something is amiss..

**Comment by jcantrill** [comment]
Interesting one of my panics comes from `log.Error(err, "Operator unable to read local file to get contents")`  so is it an issue encoding the error?

**Comment by blockloop** [comment]
@jcantrill probably. Do you know what's in the error?

**Comment by jcantrill** [comment]
I built into an image and its not crashing my container so maybe its only a local problem

**Comment by blockloop** [comment]
@jcantrill did you figure out if this was related to logerr or something else?

**Comment by vparfonov** [comment]
@jcantrill Can you reproduce this issue now?
